//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicadores_Economicos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANSWER
    {
        public int idAnswer { get; set; }
        public string author { get; set; }
        public System.DateTime startdate { get; set; }
        public string content { get; set; }
        public int idQuestion { get; set; }
    
        public virtual QUESTION QUESTION { get; set; }
    }
}
