//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indicadores_Economicos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class SUBSCRIPTION
    {
        public int idUser { get; set; }
        [DisplayName("Nombre Completo")]
        public string fullname { get; set; }
        [DisplayName("Cedula")]
        public string identificationCard { get; set; }
        [DisplayName("Edad")]
        public int age { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Profesion")]
        public string profesion { get; set; }
        [DisplayName("Provincia")]
        public int idProvince { get; set; }
        [DisplayName("Canton")]
        public string canton { get; set; }
        [DisplayName("Distrito")]
        public string district { get; set; }
        [DisplayName("Provincia")]
        public virtual PROVINCE PROVINCE { get; set; }
    }
}
